---
- hosts: scapegoat.test
  become: true
  user: "{{ansible_user}}"
  roles:
    - common
    - login_user
    - php
    - apache
    - mysql

- hosts: attacker.test
  become: true
  user: "{{ansible_user}}"
  roles:
    - common
    - login_user
    - python

