---
 - name: install apache and openssl package
   apt: name={{ item }} state=present
   with_items:
     - php5
     - php5-mysql
     - php-pear
     - php5-gd

 - name: apache runnning and enabled
   service: name=apache2 state=restarted enabled=yes

