version: "3.9"

services:
  bind9:
    image: "internetsystemsconsortium/bind9:9.11"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "127.0.0.1:953:953/tcp"
    volumes:
      - "./bind:/etc/bind"
