version: '3'
services:
    web:
        image: 'bitnami/testlink:1.9.20-debian-10-r12'
        container_name: web
        environment:
            - MARIADB_HOST=mariadb
            - MARIADB_PORT_NUMBER=3306
            - TESTLINK_DATABASE_USER=bn_testlink
            - TESTLINK_DATABASE_NAME=bitnami_testlink
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "8000:80"
        volumes:
            - 'testlink_data:/bitnami'  
        depends_on:
            - mariadb
        restart: always
        stdin_open: true
        tty: true 
    mariadb:
        image: 'bitnami/mariadb:10.3'
        environment:
            - MARIADB_USER=bn_testlink
            - MARIADB_DATABASE=bitnami_testlink
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - 'mariadb_data:/bitnami'
    config:
        build:
            context: .
            dockerfile: Dockerfile_config
        container_name: config
        depends_on:
            - web
    poc:
        build:
            context: .
            dockerfile: Dockerfile_poc
        container_name: poc
        depends_on:
            - web
            - config

volumes:
    mariadb_data: 
        driver: local
    testlink_data: 
        driver: local


    